const phrases = [
  "How are you today?",
  "I am feeling much better now.",
  "What are you doing right now?",
  "I will talk to you later.",
  "Please wait for a moment.",
  "That sounds good to me.",
  "I don’t understand this.",
  "Can you explain it again?",
  "Let me think about it.",
  "I agree with you.",
  "I don’t think so.",
  "It depends on the situation.",
  "Everything is ready.",
  "I am running late.",
  "Take care of yourself.",
  "See you tomorrow.",
  "What do you mean?",
  "That’s not a problem.",
  "I am not sure about it.",
  "Let’s start now.",
  "How are you today?",
  "I am feeling much better now.",
  "What are you doing right now?",
  "I will talk to you later.",
  "Please wait for a moment.",
  "That sounds good to me.",
  "I don’t understand this.",
  "Can you explain it again?",
  "Let me think about it.",
  "I agree with you.",
  "I don’t think so.",
  "It depends on the situation.",
  "Everything is ready.",
  "I am running late.",
  "Take care of yourself.",
  "See you tomorrow.",
  "What do you mean?",
  "That’s not a problem.",
  "I am not sure about it.",
  "Let’s start now.",
  "How are you today?",
  "I am feeling much better now.",
  "What are you doing right now?",
  "I will talk to you later.",
  "Please wait for a moment.",
  "That sounds good to me.",
  "I don’t understand this.",
  "Can you explain it again?",
  "Let me think about it.",
  "I agree with you.",
  "I don’t think so.",
  "It depends on the situation.",
  "Everything is ready.",
  "I am running late.",
  "Take care of yourself.",
  "See you tomorrow.",
  "What do you mean?",
  "That’s not a problem.",
  "I am not sure about it.",
  "Let’s start now.",
  "How are you today?",
  "I am feeling much better now.",
  "What are you doing right now?",
  "I will talk to you later.",
  "Please wait for a moment.",
  "That sounds good to me.",
  "I don’t understand this.",
  "Can you explain it again?",
  "Let me think about it.",
  "I agree with you.",
  "I don’t think so.",
  "It depends on the situation.",
  "Everything is ready.",
  "I am running late.",
  "Take care of yourself.",
  "See you tomorrow.",
  "What do you mean?",
  "That’s not a problem.",
  "I am not sure about it.",
  "Let’s start now.",
  "How are you today?",
  "I am feeling much better now.",
  "What are you doing right now?",
  "I will talk to you later.",
  "Please wait for a moment.",
  "That sounds good to me.",
  "I don’t understand this.",
  "Can you explain it again?",
  "Let me think about it.",
  "I agree with you.",
  "I don’t think so.",
  "It depends on the situation.",
  "Everything is ready.",
  "I am running late.",
  "Take care of yourself.",
  "See you tomorrow.",
  "What do you mean?",
  "That’s not a problem.",
  "I am not sure about it.",
  "Let’s start now.",
  "At Home",
  "Please turn off the lights.",
  "Dinner is ready.",
  "Clean your room properly.",
  "I am going to sleep.",
  "Wake me up at six.",
  "The door is locked.",
  "Where did you put the keys?",
  "I am feeling tired.",
  "Let’s watch TV.",
  "The house is quiet today.",
  "Please close the window.",
  "The food smells good.",
  "I need to rest for a while.",
  "Bring me a glass of water.",
  "The fan is not working.",
  "It’s time for prayer.",
  "I will cook today.",
  "The room is messy.",
  "Please answer the door.",
  "The guests have arrived.",
  "Please turn off the lights.",
  "Dinner is ready.",
  "Clean your room properly.",
  "I am going to sleep.",
  "Wake me up at six.",
  "The door is locked.",
  "Where did you put the keys?",
  "I am feeling tired.",
  "Let’s watch TV.",
  "The house is quiet today.",
  "Please close the window.",
  "The food smells good.",
  "I need to rest for a while.",
  "Bring me a glass of water.",
  "The fan is not working.",
  "It’s time for prayer.",
  "I will cook today.",
  "The room is messy.",
  "Please answer the door.",
  "The guests have arrived.",
  "Please turn off the lights.",
  "Dinner is ready.",
  "Clean your room properly.",
  "I am going to sleep.",
  "Wake me up at six.",
  "The door is locked.",
  "Where did you put the keys?",
  "I am feeling tired.",
  "Let’s watch TV.",
  "The house is quiet today.",
  "Please close the window.",
  "The food smells good.",
  "I need to rest for a while.",
  "Bring me a glass of water.",
  "The fan is not working.",
  "It’s time for prayer.",
  "I will cook today.",
  "The room is messy.",
  "Please answer the door.",
  "The guests have arrived.",
  "Please turn off the lights.",
  "Dinner is ready.",
  "Clean your room properly.",
  "I am going to sleep.",
  "Wake me up at six.",
  "The door is locked.",
  "Where did you put the keys?",
  "I am feeling tired.",
  "Let’s watch TV.",
  "The house is quiet today.",
  "Please close the window.",
  "The food smells good.",
  "I need to rest for a while.",
  "Bring me a glass of water.",
  "The fan is not working.",
  "It’s time for prayer.",
  "I will cook today.",
  "The room is messy.",
  "Please answer the door.",
  "The guests have arrived.",
  "Please turn off the lights.",
  "Dinner is ready.",
  "Clean your room properly.",
  "I am going to sleep.",
  "Wake me up at six.",
  "The door is locked.",
  "Where did you put the keys?",
  "I am feeling tired.",
  "Let’s watch TV.",
  "The house is quiet today.",
  "Please close the window.",
  "The food smells good.",
  "I need to rest for a while.",
  "Bring me a glass of water.",
  "The fan is not working.",
  "It’s time for prayer.",
  "I will cook today.",
  "The room is messy.",
  "Please answer the door.",
  "The guests have arrived.",
  "At School",
  "Open your books.",
  "Listen carefully to the teacher.",
  "Write your name here.",
  "Complete your homework on time.",
  "The class will start soon.",
  "Raise your hand to speak.",
  "The exam is tomorrow.",
  "I forgot my notebook.",
  "Please sit quietly.",
  "The bell has rung.",
  "Submit your assignment today.",
  "The teacher is absent.",
  "Revise this lesson.",
  "The result will be announced soon.",
  "Don’t make noise.",
  "Follow the instructions.",
  "The test was easy.",
  "I need extra time.",
  "The classroom is clean.",
  "School is closed today.",
  "Open your books.",
  "Listen carefully to the teacher.",
  "Write your name here.",
  "Complete your homework on time.",
  "The class will start soon.",
  "Raise your hand to speak.",
  "The exam is tomorrow.",
  "I forgot my notebook.",
  "Please sit quietly.",
  "The bell has rung.",
  "Submit your assignment today.",
  "The teacher is absent.",
  "Revise this lesson.",
  "The result will be announced soon.",
  "Don’t make noise.",
  "Follow the instructions.",
  "The test was easy.",
  "I need extra time.",
  "The classroom is clean.",
  "School is closed today.",
  "Open your books.",
  "Listen carefully to the teacher.",
  "Write your name here.",
  "Complete your homework on time.",
  "The class will start soon.",
  "Raise your hand to speak.",
  "The exam is tomorrow.",
  "I forgot my notebook.",
  "Please sit quietly.",
  "The bell has rung.",
  "Submit your assignment today.",
  "The teacher is absent.",
  "Revise this lesson.",
  "The result will be announced soon.",
  "Don’t make noise.",
  "Follow the instructions.",
  "The test was easy.",
  "I need extra time.",
  "The classroom is clean.",
  "School is closed today.",
  "Open your books.",
  "Listen carefully to the teacher.",
  "Write your name here.",
  "Complete your homework on time.",
  "The class will start soon.",
  "Raise your hand to speak.",
  "The exam is tomorrow.",
  "I forgot my notebook.",
  "Please sit quietly.",
  "The bell has rung.",
  "Submit your assignment today.",
  "The teacher is absent.",
  "Revise this lesson.",
  "The result will be announced soon.",
  "Don’t make noise.",
  "Follow the instructions.",
  "The test was easy.",
  "I need extra time.",
  "The classroom is clean.",
  "School is closed today.",
  "Open your books.",
  "Listen carefully to the teacher.",
  "Write your name here.",
  "Complete your homework on time.",
  "The class will start soon.",
  "Raise your hand to speak.",
  "The exam is tomorrow.",
  "I forgot my notebook.",
  "Please sit quietly.",
  "The bell has rung.",
  "Submit your assignment today.",
  "The teacher is absent.",
  "Revise this lesson.",
  "The result will be announced soon.",
  "Don’t make noise.",
  "Follow the instructions.",
  "The test was easy.",
  "I need extra time.",
  "The classroom is clean.",
  "School is closed today.",
  "At Office / Work",
  "Please check your email.",
  "The meeting starts at ten.",
  "I will finish this task today.",
  "Let’s discuss this issue.",
  "The report is ready.",
  "Please sign this document.",
  "I am busy right now.",
  "We need more time.",
  "The deadline is tomorrow.",
  "I will call the client.",
  "This file is important.",
  "The boss is in a meeting.",
  "Let’s take a short break.",
  "The project is delayed.",
  "Send me the details.",
  "I am working on it.",
  "The office is closed.",
  "Please update me.",
  "The work is completed.",
  "I need your approval.",
  "Please check your email.",
  "The meeting starts at ten.",
  "I will finish this task today.",
  "Let’s discuss this issue.",
  "The report is ready.",
  "Please sign this document.",
  "I am busy right now.",
  "We need more time.",
  "The deadline is tomorrow.",
  "I will call the client.",
  "This file is important.",
  "The boss is in a meeting.",
  "Let’s take a short break.",
  "The project is delayed.",
  "Send me the details.",
  "I am working on it.",
  "The office is closed.",
  "Please update me.",
  "The work is completed.",
  "I need your approval.",
  "Please check your email.",
  "The meeting starts at ten.",
  "I will finish this task today.",
  "Let’s discuss this issue.",
  "The report is ready.",
  "Please sign this document.",
  "I am busy right now.",
  "We need more time.",
  "The deadline is tomorrow.",
  "I will call the client.",
  "This file is important.",
  "The boss is in a meeting.",
  "Let’s take a short break.",
  "The project is delayed.",
  "Send me the details.",
  "I am working on it.",
  "The office is closed.",
  "Please update me.",
  "The work is completed.",
  "I need your approval.",
  "Please check your email.",
  "The meeting starts at ten.",
  "I will finish this task today.",
  "Let’s discuss this issue.",
  "The report is ready.",
  "Please sign this document.",
  "I am busy right now.",
  "We need more time.",
  "The deadline is tomorrow.",
  "I will call the client.",
  "This file is important.",
  "The boss is in a meeting.",
  "Let’s take a short break.",
  "The project is delayed.",
  "Send me the details.",
  "I am working on it.",
  "The office is closed.",
  "Please update me.",
  "The work is completed.",
  "I need your approval.",
  "Please check your email.",
  "The meeting starts at ten.",
  "I will finish this task today.",
  "Let’s discuss this issue.",
  "The report is ready.",
  "Please sign this document.",
  "I am busy right now.",
  "We need more time.",
  "The deadline is tomorrow.",
  "I will call the client.",
  "This file is important.",
  "The boss is in a meeting.",
  "Let’s take a short break.",
  "The project is delayed.",
  "Send me the details.",
  "I am working on it.",
  "The office is closed.",
  "Please update me.",
  "The work is completed.",
  "I need your approval.",
  "Shopping",
  "How much does this cost?",
  "Do you have another size?",
  "This is too expensive.",
  "Can you give a discount?",
  "I am just looking.",
  "I will buy this.",
  "Do you accept cards?",
  "The quality is good.",
  "I need a receipt.",
  "This color looks nice.",
  "Is it available in black?",
  "I want to return this.",
  "The price is reasonable.",
  "Please pack this properly.",
  "I need a shopping bag.",
  "Is there any sale?",
  "This shop is crowded.",
  "I like this design.",
  "The fabric is soft.",
  "I will pay in cash.",
  "How much does this cost?",
  "Do you have another size?",
  "This is too expensive.",
  "Can you give a discount?",
  "I am just looking.",
  "I will buy this.",
  "Do you accept cards?",
  "The quality is good.",
  "I need a receipt.",
  "This color looks nice.",
  "Is it available in black?",
  "I want to return this.",
  "The price is reasonable.",
  "Please pack this properly.",
  "I need a shopping bag.",
  "Is there any sale?",
  "This shop is crowded.",
  "I like this design.",
  "The fabric is soft.",
  "I will pay in cash.",
  "How much does this cost?",
  "Do you have another size?",
  "This is too expensive.",
  "Can you give a discount?",
  "I am just looking.",
  "I will buy this.",
  "Do you accept cards?",
  "The quality is good.",
  "I need a receipt.",
  "This color looks nice.",
  "Is it available in black?",
  "I want to return this.",
  "The price is reasonable.",
  "Please pack this properly.",
  "I need a shopping bag.",
  "Is there any sale?",
  "This shop is crowded.",
  "I like this design.",
  "The fabric is soft.",
  "I will pay in cash.",
  "How much does this cost?",
  "Do you have another size?",
  "This is too expensive.",
  "Can you give a discount?",
  "I am just looking.",
  "I will buy this.",
  "Do you accept cards?",
  "The quality is good.",
  "I need a receipt.",
  "This color looks nice.",
  "Is it available in black?",
  "I want to return this.",
  "The price is reasonable.",
  "Please pack this properly.",
  "I need a shopping bag.",
  "Is there any sale?",
  "This shop is crowded.",
  "I like this design.",
  "The fabric is soft.",
  "I will pay in cash.",
  "How much does this cost?",
  "Do you have another size?",
  "This is too expensive.",
  "Can you give a discount?",
  "I am just looking.",
  "I will buy this.",
  "Do you accept cards?",
  "The quality is good.",
  "I need a receipt.",
  "This color looks nice.",
  "Is it available in black?",
  "I want to return this.",
  "The price is reasonable.",
  "Please pack this properly.",
  "I need a shopping bag.",
  "Is there any sale?",
  "This shop is crowded.",
  "I like this design.",
  "The fabric is soft.",
  "I will pay in cash.",
  "Travel and Transport",
  "What time is the bus?",
  "I need a taxi.",
  "How far is the station?",
  "The train is late.",
  "Please book my ticket.",
  "Where is the washroom?",
  "I am new to this city.",
  "Show me the way.",
  "The road is busy.",
  "I missed my bus.",
  "Is this seat free?",
  "Stop here please.",
  "How long will it take?",
  "The traffic is heavy.",
  "I need directions.",
  "The flight is delayed.",
  "Please fasten your seatbelt.",
  "I lost my luggage.",
  "The hotel is nearby.",
  "Enjoy your journey.",
  "What time is the bus?",
  "I need a taxi.",
  "How far is the station?",
  "The train is late.",
  "Please book my ticket.",
  "Where is the washroom?",
  "I am new to this city.",
  "Show me the way.",
  "The road is busy.",
  "I missed my bus.",
  "Is this seat free?",
  "Stop here please.",
  "How long will it take?",
  "The traffic is heavy.",
  "I need directions.",
  "The flight is delayed.",
  "Please fasten your seatbelt.",
  "I lost my luggage.",
  "The hotel is nearby.",
  "Enjoy your journey.",
  "What time is the bus?",
  "I need a taxi.",
  "How far is the station?",
  "The train is late.",
  "Please book my ticket.",
  "Where is the washroom?",
  "I am new to this city.",
  "Show me the way.",
  "The road is busy.",
  "I missed my bus.",
  "Is this seat free?",
  "Stop here please.",
  "How long will it take?",
  "The traffic is heavy.",
  "I need directions.",
  "The flight is delayed.",
  "Please fasten your seatbelt.",
  "I lost my luggage.",
  "The hotel is nearby.",
  "Enjoy your journey.",
  "What time is the bus?",
  "I need a taxi.",
  "How far is the station?",
  "The train is late.",
  "Please book my ticket.",
  "Where is the washroom?",
  "I am new to this city.",
  "Show me the way.",
  "The road is busy.",
  "I missed my bus.",
  "Is this seat free?",
  "Stop here please.",
  "How long will it take?",
  "The traffic is heavy.",
  "I need directions.",
  "The flight is delayed.",
  "Please fasten your seatbelt.",
  "I lost my luggage.",
  "The hotel is nearby.",
  "Enjoy your journey.",
  "What time is the bus?",
  "I need a taxi.",
  "How far is the station?",
  "The train is late.",
  "Please book my ticket.",
  "Where is the washroom?",
  "I am new to this city.",
  "Show me the way.",
  "The road is busy.",
  "I missed my bus.",
  "Is this seat free?",
  "Stop here please.",
  "How long will it take?",
  "The traffic is heavy.",
  "I need directions.",
  "The flight is delayed.",
  "Please fasten your seatbelt.",
  "I lost my luggage.",
  "The hotel is nearby.",
  "Enjoy your journey.",
  "Phone and Online Conversation",
  "Can you hear me clearly?",
  "I will call you back.",
  "The signal is weak.",
  "Please send me a message.",
  "I missed your call.",
  "Let’s talk later.",
  "The call got disconnected.",
  "I will text you.",
  "Please check WhatsApp.",
  "I am in a meeting.",
  "The internet is slow.",
  "Send me the link.",
  "Join the call now.",
  "Mute your microphone.",
  "The video is clear.",
  "Please reply soon.",
  "I am offline now.",
  "Let’s do a video call.",
  "Share your screen.",
  "Thank you for calling.",
  "Can you hear me clearly?",
  "I will call you back.",
  "The signal is weak.",
  "Please send me a message.",
  "I missed your call.",
  "Let’s talk later.",
  "The call got disconnected.",
  "I will text you.",
  "Please check WhatsApp.",
  "I am in a meeting.",
  "The internet is slow.",
  "Send me the link.",
  "Join the call now.",
  "Mute your microphone.",
  "The video is clear.",
  "Please reply soon.",
  "I am offline now.",
  "Let’s do a video call.",
  "Share your screen.",
  "Thank you for calling.",
  "Can you hear me clearly?",
  "I will call you back.",
  "The signal is weak.",
  "Please send me a message.",
  "I missed your call.",
  "Let’s talk later.",
  "The call got disconnected.",
  "I will text you.",
  "Please check WhatsApp.",
  "I am in a meeting.",
  "The internet is slow.",
  "Send me the link.",
  "Join the call now.",
  "Mute your microphone.",
  "The video is clear.",
  "Please reply soon.",
  "I am offline now.",
  "Let’s do a video call.",
  "Share your screen.",
  "Thank you for calling.",
  "Can you hear me clearly?",
  "I will call you back.",
  "The signal is weak.",
  "Please send me a message.",
  "I missed your call.",
  "Let’s talk later.",
  "The call got disconnected.",
  "I will text you.",
  "Please check WhatsApp.",
  "I am in a meeting.",
  "The internet is slow.",
  "Send me the link.",
  "Join the call now.",
  "Mute your microphone.",
  "The video is clear.",
  "Please reply soon.",
  "I am offline now.",
  "Let’s do a video call.",
  "Share your screen.",
  "Thank you for calling.",
  "Can you hear me clearly?",
  "I will call you back.",
  "The signal is weak.",
  "Please send me a message.",
  "I missed your call.",
  "Let’s talk later.",
  "The call got disconnected.",
  "I will text you.",
  "Please check WhatsApp.",
  "I am in a meeting.",
  "The internet is slow.",
  "Send me the link.",
  "Join the call now.",
  "Mute your microphone.",
  "The video is clear.",
  "Please reply soon.",
  "I am offline now.",
  "Let’s do a video call.",
  "Share your screen.",
  "Thank you for calling.",
  "Health and Doctor Visit",
  "I am not feeling well.",
  "I have a headache.",
  "Where does it hurt?",
  "I need to see a doctor.",
  "Take this medicine daily.",
  "Get some rest.",
  "The fever is high.",
  "I feel dizzy.",
  "Do you have any allergies?",
  "The pain is severe.",
  "Follow this diet.",
  "Drink more water.",
  "You need a blood test.",
  "The report is normal.",
  "I feel better today.",
  "Avoid junk food.",
  "Take proper sleep.",
  "Come for a follow-up.",
  "The swelling is gone.",
  "I need a prescription.",
  "I am not feeling well.",
  "I have a headache.",
  "Where does it hurt?",
  "I need to see a doctor.",
  "Take this medicine daily.",
  "Get some rest.",
  "The fever is high.",
  "I feel dizzy.",
  "Do you have any allergies?",
  "The pain is severe.",
  "Follow this diet.",
  "Drink more water.",
  "You need a blood test.",
  "The report is normal.",
  "I feel better today.",
  "Avoid junk food.",
  "Take proper sleep.",
  "Come for a follow-up.",
  "The swelling is gone.",
  "I need a prescription.",
  "I am not feeling well.",
  "I have a headache.",
  "Where does it hurt?",
  "I need to see a doctor.",
  "Take this medicine daily.",
  "Get some rest.",
  "The fever is high.",
  "I feel dizzy.",
  "Do you have any allergies?",
  "The pain is severe.",
  "Follow this diet.",
  "Drink more water.",
  "You need a blood test.",
  "The report is normal.",
  "I feel better today.",
  "Avoid junk food.",
  "Take proper sleep.",
  "Come for a follow-up.",
  "The swelling is gone.",
  "I need a prescription.",
  "I am not feeling well.",
  "I have a headache.",
  "Where does it hurt?",
  "I need to see a doctor.",
  "Take this medicine daily.",
  "Get some rest.",
  "The fever is high.",
  "I feel dizzy.",
  "Do you have any allergies?",
  "The pain is severe.",
  "Follow this diet.",
  "Drink more water.",
  "You need a blood test.",
  "The report is normal.",
  "I feel better today.",
  "Avoid junk food.",
  "Take proper sleep.",
  "Come for a follow-up.",
  "The swelling is gone.",
  "I need a prescription.",
  "I am not feeling well.",
  "I have a headache.",
  "Where does it hurt?",
  "I need to see a doctor.",
  "Take this medicine daily.",
  "Get some rest.",
  "The fever is high.",
  "I feel dizzy.",
  "Do you have any allergies?",
  "The pain is severe.",
  "Follow this diet.",
  "Drink more water.",
  "You need a blood test.",
  "The report is normal.",
  "I feel better today.",
  "Avoid junk food.",
  "Take proper sleep.",
  "Come for a follow-up.",
  "The swelling is gone.",
  "I need a prescription.",
  "Restaurant and Food",
  "Can I see the menu?",
  "I would like to order.",
  "The food is delicious.",
  "Please bring some water.",
  "This dish is spicy.",
  "I want something sweet.",
  "The service is good.",
  "Can we have the bill?",
  "I am full now.",
  "The soup is hot.",
  "Please pack the leftovers.",
  "The table is reserved.",
  "I prefer vegetarian food.",
  "This tastes great.",
  "The food is cold.",
  "Please hurry up.",
  "I like this restaurant.",
  "The waiter is polite.",
  "Add less salt.",
  "Thank you for the meal.",
  "Can I see the menu?",
  "I would like to order.",
  "The food is delicious.",
  "Please bring some water.",
  "This dish is spicy.",
  "I want something sweet.",
  "The service is good.",
  "Can we have the bill?",
  "I am full now.",
  "The soup is hot.",
  "Please pack the leftovers.",
  "The table is reserved.",
  "I prefer vegetarian food.",
  "This tastes great.",
  "The food is cold.",
  "Please hurry up.",
  "I like this restaurant.",
  "The waiter is polite.",
  "Add less salt.",
  "Thank you for the meal.",
  "Can I see the menu?",
  "I would like to order.",
  "The food is delicious.",
  "Please bring some water.",
  "This dish is spicy.",
  "I want something sweet.",
  "The service is good.",
  "Can we have the bill?",
  "I am full now.",
  "The soup is hot.",
  "Please pack the leftovers.",
  "The table is reserved.",
  "I prefer vegetarian food.",
  "This tastes great.",
  "The food is cold.",
  "Please hurry up.",
  "I like this restaurant.",
  "The waiter is polite.",
  "Add less salt.",
  "Thank you for the meal.",
  "Can I see the menu?",
  "I would like to order.",
  "The food is delicious.",
  "Please bring some water.",
  "This dish is spicy.",
  "I want something sweet.",
  "The service is good.",
  "Can we have the bill?",
  "I am full now.",
  "The soup is hot.",
  "Please pack the leftovers.",
  "The table is reserved.",
  "I prefer vegetarian food.",
  "This tastes great.",
  "The food is cold.",
  "Please hurry up.",
  "I like this restaurant.",
  "The waiter is polite.",
  "Add less salt.",
  "Thank you for the meal.",
  "Can I see the menu?",
  "I would like to order.",
  "The food is delicious.",
  "Please bring some water.",
  "This dish is spicy.",
  "I want something sweet.",
  "The service is good.",
  "Can we have the bill?",
  "I am full now.",
  "The soup is hot.",
  "Please pack the leftovers.",
  "The table is reserved.",
  "I prefer vegetarian food.",
  "This tastes great.",
  "The food is cold.",
  "Please hurry up.",
  "I like this restaurant.",
  "The waiter is polite.",
  "Add less salt.",
  "Thank you for the meal.",
  "Polite and Formal Situations",
  "Excuse me, please.",
  "Thank you very much.",
  "I really appreciate it.",
  "May I come in?",
  "Please forgive me.",
  "I am sorry for the delay.",
  "Could you help me?",
  "Nice to meet you.",
  "Please take a seat.",
  "I am grateful to you.",
  "It was my pleasure.",
  "Thank you for your time.",
  "Please accept my apology.",
  "With due respect.",
  "I would like to request.",
  "Kindly inform me.",
  "Please let me know.",
  "I look forward to it.",
  "Thank you for your support.",
  "Have a nice day.",
  "Excuse me, please.",
  "Thank you very much.",
  "I really appreciate it.",
  "May I come in?",
  "Please forgive me.",
  "I am sorry for the delay.",
  "Could you help me?",
  "Nice to meet you.",
  "Please take a seat.",
  "I am grateful to you.",
  "It was my pleasure.",
  "Thank you for your time.",
  "Please accept my apology.",
  "With due respect.",
  "I would like to request.",
  "Kindly inform me.",
  "Please let me know.",
  "I look forward to it.",
  "Thank you for your support.",
  "Have a nice day.",
  "Excuse me, please.",
  "Thank you very much.",
  "I really appreciate it.",
  "May I come in?",
  "Please forgive me.",
  "I am sorry for the delay.",
  "Could you help me?",
  "Nice to meet you.",
  "Please take a seat.",
  "I am grateful to you.",
  "It was my pleasure.",
  "Thank you for your time.",
  "Please accept my apology.",
  "With due respect.",
  "I would like to request.",
  "Kindly inform me.",
  "Please let me know.",
  "I look forward to it.",
  "Thank you for your support.",
  "Have a nice day.",
  "Excuse me, please.",
  "Thank you very much.",
  "I really appreciate it.",
  "May I come in?",
  "Please forgive me.",
  "I am sorry for the delay.",
  "Could you help me?",
  "Nice to meet you.",
  "Please take a seat.",
  "I am grateful to you.",
  "It was my pleasure.",
  "Thank you for your time.",
  "Please accept my apology.",
  "With due respect.",
  "I would like to request.",
  "Kindly inform me.",
  "Please let me know.",
  "I look forward to it.",
  "Thank you for your support.",
  "Have a nice day.",
  "Excuse me, please.",
  "Thank you very much.",
  "I really appreciate it.",
  "May I come in?",
  "Please forgive me.",
  "I am sorry for the delay.",
  "Could you help me?",
  "Nice to meet you.",
  "Please take a seat.",
  "I am grateful to you.",
  "It was my pleasure.",
  "Thank you for your time.",
  "Please accept my apology.",
  "With due respect.",
  "I would like to request.",
  "Kindly inform me.",
  "Please let me know.",
  "I look forward to it.",
  "Thank you for your support.",
  "Have a nice day."
];